name: Convert Wiki to PDF

on:
  # TODO: wiki changes need a separate workflow
  push:
    paths-ignore:
      - '**.md' # README and friends; NOT the same as wiki changes
  pull_request:
    paths-ignore:
      - '**.md' # README and friends; NOT the same as wiki changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install missing tools
        run: |
          # sudo apt-get install -y pandoc texlive-xetex fonts-noto-core fonts-noto-unhinted fonts-noto-extra git
          sudo apt update
          sudo apt install git pandoc
          sudo snap install typst

      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Clone wiki repo
        run: git clone https://github.com/${{ github.repository }}.wiki.git wiki

      - name: Create page list from _Sidebar.md
        run: |
          cd wiki
          grep '\[\[' _Sidebar.md | sed 's/.*\[\[\(.*\)\]\].*/\1.md/' > ../page-list.txt
          cd ..

      - name: Generate PDF from sidebar
        run: ./wiki-to-pdf.sh --output=wiki-docs.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: wiki-docs
          path: wiki-docs.pdf
