name: Convert Wiki to PDF

on:
  # TODO: wiki changes need a separate workflow
  push:
    paths-ignore:
      - '**.md' # README and friends; NOT the same as wiki changes
  pull_request:
    paths-ignore:
      - '**.md' # README and friends; NOT the same as wiki changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install missing tools
        run: |
          sudo apt update
          sudo apt install git pandoc
          sudo snap install typst

      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Update wiki files
        run: |
          git submodule init
          git submodule update

      - name: Generate PDF
        run: ./wiki-to-pdf.sh

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: wiki-docs
          path: wiki-docs.pdf
