name: Convert Wiki to PDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Install Pandoc and XeLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex fonts-noto-core fonts-noto-unhinted fonts-noto-extra git

      - name: Clone wiki repo
        run: git clone https://github.com/${{ github.repository }}.wiki.git wiki

      - name: Create page list from _Sidebar.md
        run: |
          cd wiki
          grep '\[\[' _Sidebar.md | sed 's/.*\[\[\(.*\)\]\].*/\1.md/' > ../page-list.txt
          cd ..

      - name: Generate PDF from sidebar
        run: ./wiki-to-pdf.sh

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: wiki-docs
          path: wiki-docs.pdf
