name: Convert Wiki to PDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Clone wiki repo
        run: git clone https://github.com/${{ github.repository }}.wiki.git wiki

      - name: Create page list from _Sidebar.md
        run: |
          cd wiki
          grep '\[\[' _Sidebar.md | sed 's/.*\[\[\(.*\)\]\].*/\1.md/' > ../page-list.txt
          cd ..

      - name: Generate PDF
        run: |
          files=$(awk '{ print "wiki/" $1 }' page-list.txt)
          pandoc $files -o wiki-docs.pdf --pdf-engine=xelatex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: wiki-docs
          path: wiki-docs.pdf
